name: curation_new_test
values:
  - key: baseUrl
    value: ''
  - key: curatorToken
    secret: true
  - key: managerToken
    secret: true
  - key: otherCuratorToken
    secret: true
  - key: audienceToken
    secret: true
  - key: programId
    value: ''
  - key: searchMarker
    value: ''
  - key: curationA
    value: ''
  - key: curationB
    value: ''
  - key: curationC
    value: ''
