server:
  port: ${service.port}


# 애플리케이션 정보
spring:
  config:
    import: secrets-prod.yml

  # JPA
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  # MySQL DB
  datasource:
    url:
    driver-class-name:
    username:
    password:


# JWT
jwt:
  secret-key: ${jwt.secret-key}

# Kakao Geocoding API
kakao:
  api:
    key: ${kakao.api.rest.api.key}
    geocoding-url: https://dapi.kakao.com/v2/local/search/address.json


# AWS S3
aws:
  s3:
    access-key: ${aws.s3.access-key}
    secret-key: ${aws.s3.secret-key}
    region: ${aws.s3.region}
    bucket: ${aws.s3.bucket}
  cloudfront:
    domain: ${aws.cloudfront.domain}



# Observability
management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never


# Logging
logging:
  level:
    root: WARN
    org.springframework: WARN
    com.digniche.muntum: INFO
    org.hibernate: WARN
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF