server:
  port: 8080


# 애플리케이션 정보
spring:
  config:
    import: "file:/home/ubuntu/muntum/app/secrets-prod.yml" # secrets-prod.yml EC2 내부 경로

  # JPA
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  # MySQL DB
  datasource:
    url: jdbc:mysql://${db.aws-rds.endpoint}:3306/${db.name}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.user}
    password: ${db.password}

  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      password: ${redis.password}

  # Batch
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

  # Mail (비밀번호 재설정 인증번호 발송)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# JWT
jwt:
  secret-key: ${jwt.secret-key}


# Kakao Geocoding API
kakao:
  api:
    key: ${kakao.api.rest.api.key}
    geocoding-url: https://dapi.kakao.com/v2/local/search/address.json


# AWS S3
aws:
  s3:
    access-key: ${aws.s3.access-key}
    secret-key: ${aws.s3.secret-key}
    region: ${aws.s3.region}
    bucket: ${aws.s3.bucket}
  cloudfront:
    domain: ${aws.cloudfront.domain}


# 사용자 분석 모니터링
amplitude:
  api-key: ${amplitude.api-key}


# Observability
management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never


# Logging
logging:
  level:
    root: WARN
    org.springframework: WARN
    com.digniche.muntum: INFO
    org.hibernate: WARN
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF