server:
  port: ${service.port}


# 애플리케이션 정보
spring:
  config:
    import: secrets-prod.yml

  # JPA
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  # MySQL DB
  datasource:
    url:
    driver-class-name:
    username:
    password:


# JWT
jwt:
  secret-key: ${JWT_SECRET_KEY}

# Kakao Geocoding API
kakao:
  api:
    key: ${KAKAO_APP_REST_API_KEY}
    geocoding-url: https://dapi.kakao.com/v2/local/search/address.json


# Observability
management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never


# Logging
logging:
  level:
    root: WARN
    org.springframework: WARN
    com.digniche.muntum: INFO
    org.hibernate: WARN
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF