server:
  shutdown: graceful


# 애플리케이션 정보
spring:
  application:
    name: Muntum
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  servlet:
    multipart: # 이미지 업로드 용량
      max-file-size: 10MB
      max-request-size: 30MB

  # Server Shutdown
  lifecycle:
    timeout-per-shutdown-phase: 30s


# JWT
jwt:
  access-token-validity-time: 3600000      # 1h = 3600000
  refresh-token-validity-time: 1209600000  # 14d * 24h = 1209600000


# Observability
management:
  metrics:
    tags:
      application: Muntum

social:
  apple:
    client-id: ${APPLE_CLIENT_ID:co.digniche.muntum}