server:
  port: 8080


# 애플리케이션 정보
spring:
  config:
    import: secrets-local.yml

  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # logging.level.org.hibernate


  # MySQL DB
  datasource:
    url: jdbc:mysql://localhost:3306/${db.name}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&sslMode=REQUIRED&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db.user}
    password: ${db.password}

  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      password: ${redis.password}

  # Batch
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

  # Mail (비밀번호 재설정 인증번호 발송)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



# JWT
jwt:
  secret-key: ${jwt.secret-key}


# Kakao Geocoding API
kakao:
  api:
    key: ${kakao.api.rest.api.key}
    geocoding-url: https://dapi.kakao.com/v2/local/search/address.json


# AWS S3
storage:
  local:
    base-path: ./uploads                               # dirPath
    base-url: http://localhost:${server.port}/uploads
# secrets 파일 적용

# Observability
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
    build:
      enabled: true

  endpoint:
    health:
      show-details: always


# Logging
logging:
  level:
    root: INFO
    com.digniche.muntum: DEBUG
    org.springframework.web: WARN
    org.springframework.security: DEBUG # ['DEBUG', 'INFO'] 인증 흐름 디버깅 시 -> DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE